### ISSUE TITLE
Error al crear Modulos en Jarvis Platform

### ISSUE THREAD

**Issue by yanethi** [hechoenlaravel/jarvis-platform#12]
Hola, tengo inconvenientes al crear un nuevo modulo.
Me arroja el sigueinte error cuando intento logearme en la aplicación:
Class 'Modules\Bancos\Providers\BancosServiceProvider' not found

Espero puedas ayudarme. Saludos

**Comment by joselfonseca** [comment]
Hola, puedes mostrarnos el composer.json de tu proyecto y como creaste el módulo por favor? gracias.

**Comment by yanethi** [comment]
Hola, luego de seguir tus indicaciones para la instalación y comprobar que funciona, ingresando a la aplicación, me dispongo a crear un modulo de Bancos, lo creo de la siguiente forma: 
**php artisan module:make bancos** 
Created : C:\xampp\htdocs\jarvis\modules/Bancos/start.php 
Created : C:\xampp\htdocs\jarvis\modules/Bancos/Http/routes.php 
Created : C:\xampp\htdocs\jarvis\modules/Bancos/module.json Created : C:\xampp\htdocs\jarvis ...

Una vez que ejecuto ese comando por consola e intento ingresar a la aplicación me arroja errores como el siguiente:
**FatalErrorException in Application.php line 575: Class 'Modules\Bancos\Providers\BancosServiceProvider' not found**

**El archivo composer.json:**

{
    "name": "hechoenlaravel/jarvis-platform",
    "description": "Platform for building modular applications",
    "keywords": ["JarvisApp", "Laravel Framework", "Business Application Platform", "BAP"],
    "license" : "MIT",
    "authors": [
        {
          "name": "Jose Luis Fonseca",
          "email": "jose@ditecnologia.com"
        }
    ],
    "type": "project",
    "require": {
        "php": ">=5.5.9",
        "laravel/framework": "5.1.*",
        "hechoenlaravel/composer-plugin": "1.0.*",
        "hechoenlaravel/jarvis-foundation": "1.0.*",
        "hechoenlaravel/jarvis-users": "1.0.*",
        "hechoenlaravel/jarvis-dashboard" : "1.0.*"
    },
    "require-dev": {
        "fzaninotto/faker": "~1.4",
        "mockery/mockery": "0.9.*",
        "phpunit/phpunit": "~4.0",
        "phpspec/phpspec": "~2.1"
    },
    "autoload": {
        "classmap": [
            "database"
        ],
        "psr-4": {
            "JarvisPlatform\\": "app/"
        }
    },
    "autoload-dev": {
        "classmap": [
            "tests/TestCase.php"
        ]
    },
    "scripts": {
        "post-install-cmd": [
            "php artisan clear-compiled",
            "php artisan optimize"
        ],
        "post-update-cmd": [
            "php artisan clear-compiled",
            "php artisan optimize"
        ],
        "post-root-package-install": [
            "php -r \"copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "php artisan key:generate"
        ]
    },
    "minimum-stability": "dev",
    "prefer-stable": true,
    "config": {
        "preferred-install": "dist"
    }
}

**Comment by yanethi** [comment]
Espero puedas orientarme. De verdad es una gran proyecto para la gestión de usuarios y roles. Felicitaciones.

![modulo](https://cloud.githubusercontent.com/assets/3747546/17539809/38f67aae-5e7f-11e6-8415-2477a94ba110.png)

**Comment by joselfonseca** [comment]
Vale,

Agrega a tu composer.json en la parte de autoload PSR4 esto:

```json
"Modules\\Bancos\\": "modules/Bancos"
```
Eso va a autocargar con PSR4 la carpeta de tu módulo.

https://github.com/hechoenlaravel/jarvis-platform/wiki/M%C3%B3dulos#tenga-en-cuenta

**Comment by joselfonseca** [comment]
A bueno y después de eso en la terminal corre

```bash
composer dump-autoload
```
Para que registre el directorio en el autoload

Me cuentas!

**Comment by yanethi** [comment]
Listo, todo perfecto! Mil gracias por el apoyo! Voy a seguir con la creación del menú!

**Comment by joselfonseca** [comment]
Perfecto. Voy a cerrar esto. También puedes ingresar al Slack de Laraveles, usualmente estoy ahi o hay mas personas de la comunidad que te pueden orientar en temas de Laravel. 

Acá solicitas la invitación, te llega un correo y creas la cuenta

http://laraveles-slack.bigcode.eu/

Después puedes loguearte en https://laraveles.slack.com/

Saludos!
