### ISSUE TITLE
Inconvenientes al Crear Menú

### ISSUE THREAD

**Issue by yanethi** [hechoenlaravel/jarvis-platform#13]
Hola, te escribo porque tengo inconvenientes a la hora de agregar un item al menú.
Seguí las indicaciones para crear el módulo y todo bien. En mi caso se llama Seguridad y quisiera que fuera un Dropdowns segun las necesidades que vayan surgiendo a futuro.

Este es mi archivo SeguridadServiceProvider.php

**<?php namespace Modules\Seguridad\Providers;

use Auth;
use MenuPing;
use Illuminate\Support\ServiceProvider;

class SeguridadServiceProvider extends ServiceProvider {

	/**
	 * Indicates if loading of the provider is deferred.
	 *
	 * @var bool
	 */
	protected $defer = false;

	/**
	 * Boot the application events.
	 *
	 * @return void
	 */
	public function boot()
	{
		$this->registerTranslations();
		$this->registerConfig();
		$this->registerViews();
    $this->registerMenu();
	}

	/**
	 * Register the service provider.
	 *
	 * @return void
	 */
	public function register()
	{
		//
	}

	/**
	 * Register config.
	 *
	 * @return void
	 */
	protected function registerConfig()
	{
		$this->publishes([
		    __DIR__.'/../Config/config.php' => config_path('seguridad.php'),
		]);
		$this->mergeConfigFrom(
		    __DIR__.'/../Config/config.php', 'seguridad'
		);
	}

	/**
	 * Register views.
	 *
	 * @return void
	 */
	public function registerViews()
	{
		$viewPath = base_path('resources/views/modules/seguridad');

		$sourcePath = __DIR__.'/../Resources/views';

		$this->publishes([
			$sourcePath => $viewPath
		]);

		$this->loadViewsFrom(array_merge(array_map(function ($path) {
			return $path . '/modules/seguridad';
		}, \Config::get('view.paths')), [$sourcePath]), 'seguridad');
	}

	/**
	 * Register translations.
	 *
	 * @return void
	 */
	public function registerTranslations()
	{
		$langPath = base_path('resources/lang/modules/seguridad');

		if (is_dir($langPath)) {
			$this->loadTranslationsFrom($langPath, 'seguridad');
		} else {
			$this->loadTranslationsFrom(__DIR__ .'/../Resources/lang', 'seguridad');
		}
	}

	/**
	 * Get the services provided by the provider.
	 *
	 * @return array
	 */
	public function provides()
	{
		return array();
	}

	public function registerMenu()
	{
			if (config('dashboard.demoDashboard')) {
					$menu = MenuPing::instance('seguridad');
					$menu->route('seguridad.demo', 'Seguridad', [], 1, ['icon' => 'fa fa-dashboard'])->hideWhen(function () {
							return Auth::guest();
					});
			}
	}

}**

**Comment by yanethi** [comment]
En la función 

public function registerMenu()
{
        if (config('dashboard.demoDashboard')) {
                $menu = MenuPing::instance('seguridad');
                $menu->route('seguridad.demo', 'Seguridad', [], 1, ['icon' => 'fa fa-dashboard'])->hideWhen(function () {
                        return Auth::guest();
                });
        }
}

Haces en el if no comprendo la siguiente línea  (config('dashboard.demoDashboard')

Espero me puedas ayudar, muchas gracias.

**Comment by FradaL** [comment]
Hola @yanethi conforme al código para un dropwdown podría servirte este de ejemplo:

``` $menu->dropdown('Inventario', function($sub){
            $sub->route('inventory', 'Ver Inventario', [], 1, ['active' => function(){
                $request = app('Illuminate\Http\Request');
                return $request->is('inventory');
            }]);
            $sub->route('inventory.new', 'Agregar Nuevo Producto', [], 2, ['active' => function(){
                $request = app('Illuminate\Http\Request');
                return $request->is('inventory/new*');
            }]);
        },4,['icon' => 'fa fa-asterisk']);```

conforme a la duda del IF, creo que lo que hace es revisar si el valor de la variable demoDashboard que se encuentra en el config es TRUE.

Espero haber ayudado.

**Comment by joselfonseca** [comment]
@yanethi El If es para verificar si en la configuración dice que debemos incluir en el menu el dashboard de ejemplo que trae el módulo dashboard. eso lo puedes obviar en tu menu.

**Comment by yanethi** [comment]
Gracias por sus comentarios, sin embargo no he podido agregar en el menú lo que requiero, creé el módulo como ustedes me explicaron, ahora lo que necesito es mostrarlo en el menú y que el mismo despliegue 2 opciones: bancos activos y bancos inactivos. De verdad he tratado de seguir las indicaciones pero no me funciona, si me pudieran ayudar con un ejemplo se los agradecería. Saludos y gracias de antemano!

**Comment by FradaL** [comment]
Podrías ingresar a al slack de laraveles es una comunidad de soporte, allá podemos ayudarte.
aquí puedes solicitar tu invitación. http://laraveles-slack.bigcode.eu/
¡Te esperamos!
