### ISSUE TITLE
Usuarios - No refresca widget al eliminar un usuario

### ISSUE THREAD

**Issue by DanteLibralato** [hechoenlaravel/jarvis-platform#2]
En Usuarios, al eliminar un usuario no refresca el widget de "USUARIOS REGISTRADOS".

**Antes de Eliminar**
![jarvisplatform_is_01](https://cloud.githubusercontent.com/assets/15239304/10733632/97a27548-7bcd-11e5-866c-6ea26bad34f6.png)

**Despues de Eliminar**
![jarvisplatform_is_02](https://cloud.githubusercontent.com/assets/15239304/10733633/97a98c20-7bcd-11e5-9a63-f5bcac0b254f.png)

**Comment by joselfonseca** [comment]
Esto ya se arregla acá https://github.com/hechoenlaravel/jarvis-users/commit/5b42a390703ffd1c669db630f5457da0ba906959 Gracias
