### ISSUE TITLE
Usuarios - No se limpian los filtros al entrar por el menú.

### ISSUE THREAD

**Issue by dantelibralato** [hechoenlaravel/jarvis-platform#3]
En Usuarios, se realiza una busqueda. Luego, se hace click en el menú Usuario, ¿no debería limpiar los filtros?, ya que se estaria entrando de nuevo a dicho menú.

**Comment by joselfonseca** [comment]
@DanteLibralato Es cómico, por que si hacemos click en ese enlace estando ya un usuarios, no cambia no reacciona el explorador, como si ya supiera que va para el mismo lado. Si vuelve a recargar la pagina si se ejecuta el request. Estoy algo confundido de por que puede pasar eso. Alguna idea?
