### ISSUE TITLE
Usuarios - Error al registro de usuario

### ISSUE THREAD

**Issue by DanteLibralato** [hechoenlaravel/jarvis-platform#4]
En Usuarios, al registrar un usuario indica el siguiente error.
![jarvisplatform_is_03](https://cloud.githubusercontent.com/assets/15239304/10734008/269d09f6-7bcf-11e5-94fc-afbf78bd439a.png)

**Comment by joselfonseca** [comment]
Esto se arregla acá https://github.com/hechoenlaravel/jarvis-users/commit/cbd2b6ea77aaea3dd383a916dc36329f7a6d5ac1 y acá https://github.com/hechoenlaravel/jarvis-users/commit/827e32fc71bf24c189f6428422b8ed37ffa36ca3 En un momento debe quedar arriba en el Demo. Gracias
