### ISSUE TITLE
Usuarios - Error al registrar usuario sin roles

### ISSUE THREAD

**Issue by DanteLibralato** [hechoenlaravel/jarvis-platform#5]
En Usuarios, al registrar un usuario, el sistema no valida que se deba seleccionar al menos 1 rol, sino sale error.
![jarvisplatform_is_03](https://cloud.githubusercontent.com/assets/15239304/10740513/a8fe2486-7bf0-11e5-9da9-0b7493850eea.png)

**Datos probados**
![jarvisplatform_is_04](https://cloud.githubusercontent.com/assets/15239304/10740655/5553e194-7bf1-11e5-93c3-31bc30256de0.png)

**Comment by joselfonseca** [comment]
@DanteLibralato Listo gracias!  se arregla con esto https://github.com/hechoenlaravel/jarvis-users/commit/061f4ec6202cbdd271bb9ed9b79def86442856e5 en unos minutos que se actualize el cache de composer sube al demo.
