### ISSUE TITLE
Bug en Seeder

### ISSUE THREAD

**Issue by FradaL** [hechoenlaravel/jarvis-platform#8]
Cuando se crea un Seeder y trata de ejecutarse con el comando `php artisan module:seed nombredelmodulo` se busca un seed llamado `nombredelmoduloTableSeeder` y no logra encontrarlo, debido a qué el que se crea en el modulo se llama nombredelmodulo**Database**Seeder

**Comment by joselfonseca** [comment]
Eso es un tema del generador de PingPong, no tiene nada que ver con Jarvis Platform. Yo siempre creo los seeders manualmente nunca uso ese comando. Le recomiendo que haga lo mismo. 

Saludos!
